In [3]:
!pip install ultralytics

Collecting ultralytics
  Using cached ultralytics-8.4.41-py3-none-any.whl.metadata (39 kB)
Collecting numpy>=1.23.0 (from ultralytics)
  Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib>=3.3.0 (from ultralytics)
  Using cached matplotlib-3.10.9-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting opencv-python>=4.6.0 (from ultralytics)
  Using cached opencv_python-4.13.0.92-cp37-abi3-win_amd64.whl.metadata (20 kB)
Collecting pillow>=7.1.2 (from ultralytics)
  Using cached pillow-12.2.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyyaml>=5.3.1 (from ultralytics)
  Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl.metadata (2.4 kB)
Collecting requests>=2.23.0 (from ultralytics)
  Using cached requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting scipy>=1.4.1 (from ultralytics)
  Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting torch>=1.8.0 (from ultralytics)
  Using cached torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
Collecting torchvision>=0.9.0 (from ultralytics)
  Using cached torchvision-0.26.0-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: psutil>=5.8.0 in c:\users\mo\appdata\roaming\python\python313\site-packages (from ultralytics) (7.2.2)
Collecting polars>=0.20.0 (from ultralytics)
  Using cached polars-1.40.1-py3-none-any.whl.metadata (10 kB)
Collecting ultralytics-thop>=2.0.18 (from ultralytics)
  Using cached ultralytics_thop-2.0.19-py3-none-any.whl.metadata (14 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=3.3.0->ultralytics)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib>=3.3.0->ultralytics)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.3.0->ultralytics)
  Using cached fonttools-4.62.1-cp313-cp313-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.3.0->ultralytics)
  Using cached kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\mo\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->ultralytics) (26.2)
Collecting pyparsing>=3 (from matplotlib>=3.3.0->ultralytics)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\mo\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Collecting polars-runtime-32==1.40.1 (from polars>=0.20.0->ultralytics)
  Using cached polars_runtime_32-1.40.1-cp310-abi3-win_amd64.whl.metadata (1.5 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.23.0->ultralytics)
  Downloading charset_normalizer-3.4.7-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests>=2.23.0->ultralytics)
  Downloading idna-3.13-py3-none-any.whl.metadata (8.0 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.23.0->ultralytics)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests>=2.23.0->ultralytics)
  Downloading certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Collecting filelock (from torch>=1.8.0->ultralytics)
  Downloading filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch>=1.8.0->ultralytics)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools<82 (from torch>=1.8.0->ultralytics)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch>=1.8.0->ultralytics)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=1.8.0->ultralytics)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch>=1.8.0->ultralytics)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch>=1.8.0->ultralytics)
  Downloading fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: six>=1.5 in c:\users\mo\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.8.0->ultralytics)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=1.8.0->ultralytics)
  Downloading markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Downloading ultralytics-8.4.41-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ----------------- ---------------------- 0.5/1.2 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 4.4 MB/s eta 0:00:00
Downloading matplotlib-3.10.9-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   -------- ------------------------------- 1.8/8.2 MB 9.8 MB/s eta 0:00:01
   -------------- ------------------------- 2.9/8.2 MB 9.7 MB/s eta 0:00:01
   -------------------------- ------------- 5.5/8.2 MB 8.6 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 9.0 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 8.6 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.3 MB 10.8 MB/s eta 0:00:01
   ------------ --------------------------- 3.9/12.3 MB 10.4 MB/s eta 0:00:01
   -------------- ------------------------- 4.5/12.3 MB 7.2 MB/s eta 0:00:02
   -------------------------- ------------- 8.1/12.3 MB 10.2 MB/s eta 0:00:01
   --------------------------------- ------ 10.2/12.3 MB 10.1 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 10.0 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 9.5 MB/s eta 0:00:00
Downloading opencv_python-4.13.0.92-cp37-abi3-win_amd64.whl (40.2 MB)
   ---------------------------------------- 0.0/40.2 MB ? eta -:--:--
   -- ------------------------------------- 2.1/40.2 MB 10.0 MB/s eta 0:00:04
   ---- ----------------------------------- 4.2/40.2 MB 10.0 MB/s eta 0:00:04
   ------ --------------------------------- 6.3/40.2 MB 10.0 MB/s eta 0:00:04
   -------- ------------------------------- 8.4/40.2 MB 9.9 MB/s eta 0:00:04
   --------- ------------------------------ 10.0/40.2 MB 9.4 MB/s eta 0:00:04
   ----------- ---------------------------- 11.5/40.2 MB 9.2 MB/s eta 0:00:04
   ------------ --------------------------- 12.8/40.2 MB 8.9 MB/s eta 0:00:04
   -------------- ------------------------- 14.7/40.2 MB 8.7 MB/s eta 0:00:03
   ---------------- ----------------------- 16.5/40.2 MB 8.6 MB/s eta 0:00:03
   ----------------- ---------------------- 18.1/40.2 MB 8.5 MB/s eta 0:00:03
   ------------------- -------------------- 19.9/40.2 MB 8.4 MB/s eta 0:00:03
   --------------------- ------------------ 21.2/40.2 MB 8.4 MB/s eta 0:00:03
   ---------------------- ----------------- 23.1/40.2 MB 8.4 MB/s eta 0:00:03
   ------------------------ --------------- 24.9/40.2 MB 8.3 MB/s eta 0:00:02
   -------------------------- ------------- 26.5/40.2 MB 8.3 MB/s eta 0:00:02
   --------------------------- ------------ 28.0/40.2 MB 8.2 MB/s eta 0:00:02
   ----------------------------- ---------- 29.6/40.2 MB 8.2 MB/s eta 0:00:02
   ------------------------------- -------- 31.2/40.2 MB 8.2 MB/s eta 0:00:02
   -------------------------------- ------- 33.0/40.2 MB 8.1 MB/s eta 0:00:01
   ---------------------------------- ----- 34.6/40.2 MB 8.1 MB/s eta 0:00:01
   ------------------------------------ --- 36.4/40.2 MB 8.1 MB/s eta 0:00:01
   ------------------------------------- -- 38.0/40.2 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------  39.6/40.2 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------  40.1/40.2 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 40.2/40.2 MB 7.9 MB/s eta 0:00:00
Downloading pillow-12.2.0-cp313-cp313-win_amd64.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   -------- ------------------------------- 1.6/7.1 MB 8.2 MB/s eta 0:00:01
   ----------------- ---------------------- 3.1/7.1 MB 8.1 MB/s eta 0:00:01
   ---------------------------- ----------- 5.0/7.1 MB 7.9 MB/s eta 0:00:01
   ------------------------------------- -- 6.6/7.1 MB 7.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.1 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 7.1/7.1 MB 2.3 MB/s eta 0:00:00
Downloading polars-1.40.1-py3-none-any.whl (828 kB)
   ---------------------------------------- 0.0/828.7 kB ? eta -:--:--
   ---------------------------------------- 828.7/828.7 kB 5.2 MB/s eta 0:00:00
Downloading polars_runtime_32-1.40.1-cp310-abi3-win_amd64.whl (51.8 MB)
   ---------------------------------------- 0.0/51.8 MB ? eta -:--:--
    --------------------------------------- 1.0/51.8 MB 5.6 MB/s eta 0:00:10
   - -------------------------------------- 2.4/51.8 MB 5.7 MB/s eta 0:00:09
   -- ------------------------------------- 3.7/51.8 MB 5.8 MB/s eta 0:00:09
   --- ------------------------------------ 5.0/51.8 MB 5.9 MB/s eta 0:00:08
   ---- ----------------------------------- 6.3/51.8 MB 6.0 MB/s eta 0:00:08
   ------ --------------------------------- 7.9/51.8 MB 6.2 MB/s eta 0:00:08
   ------- -------------------------------- 9.2/51.8 MB 6.2 MB/s eta 0:00:07
   -------- ------------------------------- 10.5/51.8 MB 6.3 MB/s eta 0:00:07
   --------- ------------------------------ 12.1/51.8 MB 6.4 MB/s eta 0:00:07
   ---------- ----------------------------- 13.6/51.8 MB 6.4 MB/s eta 0:00:06
   ----------- ---------------------------- 15.2/51.8 MB 6.5 MB/s eta 0:00:06
   ------------ --------------------------- 16.8/51.8 MB 6.6 MB/s eta 0:00:06
   -------------- ------------------------- 18.4/51.8 MB 6.6 MB/s eta 0:00:06
   --------------- ------------------------ 19.9/51.8 MB 6.7 MB/s eta 0:00:05
   ---------------- ----------------------- 21.5/51.8 MB 6.7 MB/s eta 0:00:05
   ----------------- ---------------------- 23.1/51.8 MB 6.8 MB/s eta 0:00:05
   ------------------- -------------------- 24.6/51.8 MB 6.8 MB/s eta 0:00:05
   -------------------- ------------------- 26.2/51.8 MB 6.8 MB/s eta 0:00:04
   --------------------- ------------------ 27.8/51.8 MB 6.9 MB/s eta 0:00:04
   ---------------------- ----------------- 29.4/51.8 MB 6.9 MB/s eta 0:00:04
   ----------------------- ---------------- 30.9/51.8 MB 6.9 MB/s eta 0:00:04
   ------------------------- -------------- 32.5/51.8 MB 7.0 MB/s eta 0:00:03
   -------------------------- ------------- 34.1/51.8 MB 7.0 MB/s eta 0:00:03
   --------------------------- ------------ 35.7/51.8 MB 7.0 MB/s eta 0:00:03
   ---------------------------- ----------- 37.5/51.8 MB 7.1 MB/s eta 0:00:03
   ------------------------------ --------- 39.1/51.8 MB 7.1 MB/s eta 0:00:02
   ------------------------------- -------- 40.9/51.8 MB 7.1 MB/s eta 0:00:02
   -------------------------------- ------- 42.5/51.8 MB 7.1 MB/s eta 0:00:02
   --------------------------------- ------ 44.0/51.8 MB 7.2 MB/s eta 0:00:02
   ----------------------------------- ---- 45.6/51.8 MB 7.2 MB/s eta 0:00:01
   ------------------------------------ --- 47.2/51.8 MB 7.2 MB/s eta 0:00:01
   ------------------------------------- -- 49.0/51.8 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  50.9/51.8 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  51.6/51.8 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------- 51.8/51.8 MB 7.1 MB/s eta 0:00:00
Downloading pyyaml-6.0.3-cp313-cp313-win_amd64.whl (154 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   - -------------------------------------- 1.6/36.5 MB 8.3 MB/s eta 0:00:05
   --- ------------------------------------ 3.1/36.5 MB 7.5 MB/s eta 0:00:05
   ----- ---------------------------------- 4.7/36.5 MB 7.5 MB/s eta 0:00:05
   ------- -------------------------------- 6.6/36.5 MB 7.5 MB/s eta 0:00:04
   -------- ------------------------------- 8.1/36.5 MB 7.6 MB/s eta 0:00:04
   ---------- ----------------------------- 10.0/36.5 MB 7.7 MB/s eta 0:00:04
   ------------ --------------------------- 11.5/36.5 MB 7.7 MB/s eta 0:00:04
   -------------- ------------------------- 13.1/36.5 MB 7.6 MB/s eta 0:00:04
   ---------------- ----------------------- 14.7/36.5 MB 7.7 MB/s eta 0:00:03
   ----------------- ---------------------- 16.3/36.5 MB 7.7 MB/s eta 0:00:03
   ------------------- -------------------- 18.1/36.5 MB 7.7 MB/s eta 0:00:03
   --------------------- ------------------ 19.7/36.5 MB 7.7 MB/s eta 0:00:03
   ----------------------- ---------------- 21.2/36.5 MB 7.7 MB/s eta 0:00:02
   ------------------------- -------------- 23.1/36.5 MB 7.7 MB/s eta 0:00:02
   -------------------------- ------------- 24.6/36.5 MB 7.7 MB/s eta 0:00:02
   ---------------------------- ----------- 26.2/36.5 MB 7.7 MB/s eta 0:00:02
   ------------------------------ --------- 28.0/36.5 MB 7.7 MB/s eta 0:00:02
   -------------------------------- ------- 29.9/36.5 MB 7.8 MB/s eta 0:00:01
   ---------------------------------- ----- 31.7/36.5 MB 7.8 MB/s eta 0:00:01
   ------------------------------------ --- 33.3/36.5 MB 7.8 MB/s eta 0:00:01
   -------------------------------------- - 34.9/36.5 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 7.7 MB/s eta 0:00:00
Downloading torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
    --------------------------------------- 1.6/114.6 MB 8.6 MB/s eta 0:00:14
   - -------------------------------------- 3.4/114.6 MB 8.5 MB/s eta 0:00:14
   - -------------------------------------- 5.2/114.6 MB 8.3 MB/s eta 0:00:14
   -- ------------------------------------- 6.8/114.6 MB 8.3 MB/s eta 0:00:14
   --- ------------------------------------ 8.7/114.6 MB 8.3 MB/s eta 0:00:13
   --- ------------------------------------ 10.2/114.6 MB 8.3 MB/s eta 0:00:13
   ---- ----------------------------------- 11.5/114.6 MB 8.0 MB/s eta 0:00:13
   ---- ----------------------------------- 13.4/114.6 MB 8.1 MB/s eta 0:00:13
   ----- ---------------------------------- 15.2/114.6 MB 8.1 MB/s eta 0:00:13
   ----- ---------------------------------- 17.0/114.6 MB 8.2 MB/s eta 0:00:12
   ------ --------------------------------- 17.6/114.6 MB 8.1 MB/s eta 0:00:12
   ------ --------------------------------- 19.9/114.6 MB 7.9 MB/s eta 0:00:13
   ------- -------------------------------- 21.2/114.6 MB 7.8 MB/s eta 0:00:12
   ------- -------------------------------- 22.8/114.6 MB 7.8 MB/s eta 0:00:12
   -------- ------------------------------- 24.4/114.6 MB 7.7 MB/s eta 0:00:12
   --------- ------------------------------ 26.0/114.6 MB 7.7 MB/s eta 0:00:12
   --------- ------------------------------ 27.3/114.6 MB 7.7 MB/s eta 0:00:12
   ---------- ----------------------------- 28.8/114.6 MB 7.6 MB/s eta 0:00:12
   ---------- ----------------------------- 30.1/114.6 MB 7.5 MB/s eta 0:00:12
   ---------- ----------------------------- 31.5/114.6 MB 7.5 MB/s eta 0:00:12
   ----------- ---------------------------- 33.0/114.6 MB 7.5 MB/s eta 0:00:11
   ------------ --------------------------- 34.6/114.6 MB 7.5 MB/s eta 0:00:11
   ------------ --------------------------- 36.2/114.6 MB 7.5 MB/s eta 0:00:11
   ------------- -------------------------- 37.5/114.6 MB 7.5 MB/s eta 0:00:11
   ------------- -------------------------- 39.3/114.6 MB 7.5 MB/s eta 0:00:10
   -------------- ------------------------- 41.2/114.6 MB 7.6 MB/s eta 0:00:10
   -------------- ------------------------- 42.7/114.6 MB 7.6 MB/s eta 0:00:10
   --------------- ------------------------ 44.6/114.6 MB 7.6 MB/s eta 0:00:10
   ---------------- ----------------------- 46.1/114.6 MB 7.6 MB/s eta 0:00:10
   ---------------- ----------------------- 48.0/114.6 MB 7.6 MB/s eta 0:00:09
   ----------------- ---------------------- 49.8/114.6 MB 7.7 MB/s eta 0:00:09
   ----------------- ---------------------- 51.4/114.6 MB 7.7 MB/s eta 0:00:09
   ------------------ --------------------- 53.5/114.6 MB 7.7 MB/s eta 0:00:08
   ------------------- -------------------- 55.3/114.6 MB 7.7 MB/s eta 0:00:08
   ------------------- -------------------- 57.1/114.6 MB 7.8 MB/s eta 0:00:08
   -------------------- ------------------- 59.0/114.6 MB 7.8 MB/s eta 0:00:08
   --------------------- ------------------ 61.1/114.6 MB 7.8 MB/s eta 0:00:07
   --------------------- ------------------ 62.7/114.6 MB 7.9 MB/s eta 0:00:07
   ---------------------- ----------------- 64.7/114.6 MB 7.9 MB/s eta 0:00:07
   ----------------------- ---------------- 66.8/114.6 MB 7.9 MB/s eta 0:00:07
   ------------------------ --------------- 68.9/114.6 MB 8.0 MB/s eta 0:00:06
   ------------------------ --------------- 70.8/114.6 MB 8.0 MB/s eta 0:00:06
   ------------------------- -------------- 72.9/114.6 MB 8.0 MB/s eta 0:00:06
   -------------------------- ------------- 74.7/114.6 MB 8.0 MB/s eta 0:00:05
   -------------------------- ------------- 76.5/114.6 MB 8.1 MB/s eta 0:00:05
   --------------------------- ------------ 78.4/114.6 MB 8.1 MB/s eta 0:00:05
   ---------------------------- ----------- 80.5/114.6 MB 8.1 MB/s eta 0:00:05
   ---------------------------- ----------- 82.3/114.6 MB 8.1 MB/s eta 0:00:04
   ----------------------------- ---------- 84.1/114.6 MB 8.1 MB/s eta 0:00:04
   ------------------------------ --------- 86.2/114.6 MB 8.2 MB/s eta 0:00:04
   ------------------------------ --------- 87.8/114.6 MB 8.2 MB/s eta 0:00:04
   ------------------------------- -------- 89.7/114.6 MB 8.2 MB/s eta 0:00:04
   ------------------------------- -------- 91.5/114.6 MB 8.2 MB/s eta 0:00:03
   -------------------------------- ------- 93.3/114.6 MB 8.2 MB/s eta 0:00:03
   --------------------------------- ------ 95.2/114.6 MB 8.2 MB/s eta 0:00:03
   --------------------------------- ------ 97.3/114.6 MB 8.2 MB/s eta 0:00:03
   ---------------------------------- ----- 99.1/114.6 MB 8.2 MB/s eta 0:00:02
   ----------------------------------- ---- 100.7/114.6 MB 8.2 MB/s eta 0:00:02
   ----------------------------------- ---- 102.8/114.6 MB 8.2 MB/s eta 0:00:02
   ------------------------------------ --- 104.6/114.6 MB 8.2 MB/s eta 0:00:02
   ------------------------------------- -- 106.4/114.6 MB 8.3 MB/s eta 0:00:01
   ------------------------------------- -- 108.3/114.6 MB 8.3 MB/s eta 0:00:01
   -------------------------------------- - 110.4/114.6 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------  112.2/114.6 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------  114.0/114.6 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------  114.3/114.6 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 114.6/114.6 MB 8.1 MB/s eta 0:00:00

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Mo\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\scipy\\interpolate\\_rbfinterp.py'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting ultralytics
  Using cached ultralytics-8.4.41-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: numpy>=1.23.0 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from ultralytics) (2.4.4)
Collecting matplotlib>=3.3.0 (from ultralytics)
  Using cached matplotlib-3.10.9-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting opencv-python>=4.6.0 (from ultralytics)
  Using cached opencv_python-4.13.0.92-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: pillow>=7.1.2 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from ultralytics) (12.2.0)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from ultralytics) (6.0.3)
Collecting requests>=2.23.0 (from ultralytics)
  Using cached requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting scipy>=1.4.1 (from ultralytics)
  Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting torch>=1.8.0 (from ultralytics)
  Using cached torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
Collecting torchvision>=0.9.0 (from ultralytics)
  Using cached torchvision-0.26.0-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: psutil>=5.8.0 in c:\users\mo\appdata\roaming\python\python313\site-packages (from ultralytics) (7.2.2)
Collecting polars>=0.20.0 (from ultralytics)
  Using cached polars-1.40.1-py3-none-any.whl.metadata (10 kB)
Collecting ultralytics-thop>=2.0.18 (from ultralytics)
  Using cached ultralytics_thop-2.0.19-py3-none-any.whl.metadata (14 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=3.3.0->ultralytics)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib>=3.3.0->ultralytics)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.3.0->ultralytics)
  Using cached fonttools-4.62.1-cp313-cp313-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=3.3.0->ultralytics)
  Using cached kiwisolver-1.5.0-cp313-cp313-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\mo\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->ultralytics) (26.2)
Requirement already satisfied: pyparsing>=3 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from matplotlib>=3.3.0->ultralytics) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\mo\appdata\roaming\python\python313\site-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: polars-runtime-32==1.40.1 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from polars>=0.20.0->ultralytics) (1.40.1)
Collecting charset_normalizer<4,>=2 (from requests>=2.23.0->ultralytics)
  Using cached charset_normalizer-3.4.7-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests>=2.23.0->ultralytics)
  Using cached idna-3.13-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.23.0->ultralytics) (2.6.3)
Collecting certifi>=2023.5.7 (from requests>=2.23.0->ultralytics)
  Using cached certifi-2026.4.22-py3-none-any.whl.metadata (2.5 kB)
Collecting filelock (from torch>=1.8.0->ultralytics)
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.8.0->ultralytics) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Collecting jinja2 (from torch>=1.8.0->ultralytics)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch>=1.8.0->ultralytics)
  Using cached fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: six>=1.5 in c:\users\mo\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Collecting MarkupSafe>=2.0 (from jinja2->torch>=1.8.0->ultralytics)
  Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Using cached ultralytics-8.4.41-py3-none-any.whl (1.2 MB)
Using cached matplotlib-3.10.9-cp313-cp313-win_amd64.whl (8.2 MB)
Using cached opencv_python-4.13.0.92-cp37-abi3-win_amd64.whl (40.2 MB)
Using cached polars-1.40.1-py3-none-any.whl (828 kB)
Using cached requests-2.33.1-py3-none-any.whl (64 kB)
Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
Using cached torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
Using cached torchvision-0.26.0-cp313-cp313-win_amd64.whl (4.3 MB)
Using cached ultralytics_thop-2.0.19-py3-none-any.whl (28 kB)
Using cached certifi-2026.4.22-py3-none-any.whl (135 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-win_amd64.whl (158 kB)
Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp313-cp313-win_amd64.whl (2.3 MB)
Using cached fsspec-2026.3.0-py3-none-any.whl (202 kB)
Using cached idna-3.13-py3-none-any.whl (68 kB)
Using cached kiwisolver-1.5.0-cp313-cp313-win_amd64.whl (73 kB)
Using cached filelock-3.29.0-py3-none-any.whl (39 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl (15 kB)
Installing collected packages: scipy, polars, opencv-python, MarkupSafe, kiwisolver, idna, fsspec, fonttools, filelock, cycler, contourpy, charset_normalizer, certifi, requests, matplotlib, jinja2, torch, ultralytics-thop, torchvision, ultralytics
Successfully installed MarkupSafe-3.0.3 certifi-2026.4.22 charset_normalizer-3.4.7 contourpy-1.3.3 cycler-0.12.1 filelock-3.29.0 fonttools-4.62.1 fsspec-2026.3.0 idna-3.13 jinja2-3.1.6 kiwisolver-1.5.0 matplotlib-3.10.9 opencv-python-4.13.0.92 polars-1.40.1 requests-2.33.1 scipy-1.17.1 torch-2.11.0 torchvision-0.26.0 ultralytics-8.4.41 ultralytics-thop-2.0.19

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="w0WrrKHoEIjB5SqpNv2E")
project = rf.workspace("sami-semir").project("my-first-project-q8ldn")
version = project.version(2)
dataset = version.download("yolov8")

[notice] A new release of pip is available: 24.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting roboflow
  Downloading roboflow-1.3.5-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: certifi in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from roboflow) (2026.4.22)
Collecting idna==3.7 (from roboflow)
  Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: cycler in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from roboflow) (0.12.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from roboflow) (1.5.0)
Requirement already satisfied: matplotlib in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from roboflow) (3.10.9)
Requirement already satisfied: numpy>=1.18.5 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from roboflow) (2.4.4)
Collecting opencv-python-headless==4.10.0.84 (from roboflow)
  Downloading opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: Pillow>=7.1.2 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from roboflow) (12.2.0)
Collecting pi-heif<2 (from roboflow)
  Downloading pi_heif-1.3.0-cp313-cp313-win_amd64.whl.metadata (6.5 kB)
Collecting pillow-avif-plugin<2 (from roboflow)
  Downloading pillow_avif_plugin-1.5.5-cp313-cp313-win_amd64.whl.metadata (2.3 kB)
Requirement already satisfied: python-dateutil in c:\users\mo\appdata\roaming\python\python313\site-packages (from roboflow) (2.9.0.post0)
Collecting python-dotenv (from roboflow)
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: requests in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from roboflow) (2.33.1)
Requirement already satisfied: six in c:\users\mo\appdata\roaming\python\python313\site-packages (from roboflow) (1.17.0)
Requirement already satisfied: urllib3>=1.26.6 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from roboflow) (2.6.3)
Collecting tqdm>=4.41.0 (from roboflow)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: PyYAML>=5.3.1 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from roboflow) (6.0.3)
Collecting requests_toolbelt (from roboflow)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting filetype (from roboflow)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting typer>=0.12.0 (from roboflow)
  Downloading typer-0.25.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: colorama in c:\users\mo\appdata\roaming\python\python313\site-packages (from tqdm>=4.41.0->roboflow) (0.4.6)
Collecting click>=8.2.1 (from typer>=0.12.0->roboflow)
  Downloading click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer>=0.12.0->roboflow)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer>=0.12.0->roboflow)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer>=0.12.0->roboflow)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->roboflow) (1.3.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->roboflow) (4.62.1)
Requirement already satisfied: packaging>=20.0 in c:\users\mo\appdata\roaming\python\python313\site-packages (from matplotlib->roboflow) (26.2)
Requirement already satisfied: pyparsing>=3 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->roboflow) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mo\appdata\local\programs\python\python313\lib\site-packages (from requests->roboflow) (3.4.7)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer>=0.12.0->roboflow)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mo\appdata\roaming\python\python313\site-packages (from rich>=13.8.0->typer>=0.12.0->roboflow) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.12.0->roboflow)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading roboflow-1.3.5-py3-none-any.whl (183 kB)
Downloading idna-3.7-py3-none-any.whl (66 kB)
Downloading opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.8 MB ? eta -:--:--
   - -------------------------------------- 1.3/38.8 MB 3.6 MB/s eta 0:00:11
   --- ------------------------------------ 3.1/38.8 MB 5.8 MB/s eta 0:00:07
   ----- ---------------------------------- 5.0/38.8 MB 6.7 MB/s eta 0:00:06
   ------- -------------------------------- 7.1/38.8 MB 7.4 MB/s eta 0:00:05
   --------- ------------------------------ 9.2/38.8 MB 7.9 MB/s eta 0:00:04
   ----------- ---------------------------- 11.5/38.8 MB 8.3 MB/s eta 0:00:04
   -------------- ------------------------- 13.6/38.8 MB 8.5 MB/s eta 0:00:03
   ---------------- ----------------------- 15.7/38.8 MB 8.6 MB/s eta 0:00:03
   ----------------- ---------------------- 17.0/38.8 MB 8.7 MB/s eta 0:00:03
   -------------------- ------------------- 19.9/38.8 MB 8.9 MB/s eta 0:00:03
   ---------------------- ----------------- 22.0/38.8 MB 9.0 MB/s eta 0:00:02
   ------------------------ --------------- 24.1/38.8 MB 9.1 MB/s eta 0:00:02
   --------------------------- ------------ 26.2/38.8 MB 9.1 MB/s eta 0:00:02
   ----------------------------- ---------- 28.6/38.8 MB 9.2 MB/s eta 0:00:02
   ------------------------------ --------- 29.9/38.8 MB 9.3 MB/s eta 0:00:01
   ------------------------------ --------- 29.9/38.8 MB 9.3 MB/s eta 0:00:01
   ------------------------------ --------- 29.9/38.8 MB 9.3 MB/s eta 0:00:01
   ------------------------------- -------- 30.7/38.8 MB 7.8 MB/s eta 0:00:02
   ------------------------------- -------- 30.9/38.8 MB 7.5 MB/s eta 0:00:02
   ------------------------------- -------- 30.9/38.8 MB 7.5 MB/s eta 0:00:02
   ------------------------------- -------- 30.9/38.8 MB 7.5 MB/s eta 0:00:02
   ------------------------------- -------- 30.9/38.8 MB 7.5 MB/s eta 0:00:02
   -------------------------------- ------- 31.2/38.8 MB 6.4 MB/s eta 0:00:02
   -------------------------------- ------- 31.2/38.8 MB 6.4 MB/s eta 0:00:02
   -------------------------------- ------- 31.5/38.8 MB 5.8 MB/s eta 0:00:02
   -------------------------------- ------- 31.7/38.8 MB 5.6 MB/s eta 0:00:02
   --------------------------------- ------ 32.5/38.8 MB 5.6 MB/s eta 0:00:02
   ----------------------------------- ---- 34.1/38.8 MB 5.6 MB/s eta 0:00:01
   ------------------------------------- -- 35.9/38.8 MB 5.7 MB/s eta 0:00:01
   -------------------------------------- - 37.5/38.8 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  38.5/38.8 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 38.8/38.8 MB 5.7 MB/s eta 0:00:00
Downloading pi_heif-1.3.0-cp313-cp313-win_amd64.whl (1.9 MB)
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   -------------------------------- ------- 1.6/1.9 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------- 1.9/1.9 MB 7.5 MB/s eta 0:00:00
Downloading pillow_avif_plugin-1.5.5-cp313-cp313-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.9 MB 8.5 MB/s eta 0:00:01
   ------------- -------------------------- 3.4/9.9 MB 8.2 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.9 MB 8.3 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 8.4 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 8.2 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Downloading typer-0.25.0-py3-none-any.whl (55 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading click-8.3.3-py3-none-any.whl (110 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pillow-avif-plugin, filetype, tqdm, shellingham, python-dotenv, pi-heif, opencv-python-headless, mdurl, idna, click, annotated-doc, markdown-it-py, rich, requests_toolbelt, typer, roboflow
  Attempting uninstall: idna
    Found existing installation: idna 3.13
    Uninstalling idna-3.13:
      Successfully uninstalled idna-3.13
Successfully installed annotated-doc-0.0.4 click-8.3.3 filetype-1.2.0 idna-3.7 markdown-it-py-4.0.0 mdurl-0.1.2 opencv-python-headless-4.10.0.84 pi-heif-1.3.0 pillow-avif-plugin-1.5.5 python-dotenv-1.2.2 requests_toolbelt-1.0.0 rich-15.0.0 roboflow-1.3.5 shellingham-1.5.4 tqdm-4.67.3 typer-0.25.0
loading Roboflow workspace...
loading Roboflow project...

Downloading Dataset Version Zip in My-First-Project-2 to yolov8:: 100%|██████████| 16058/16058 [00:03<00:00, 5057.71it/s]

Extracting Dataset Version Zip to My-First-Project-2 in yolov8:: 100%|██████████| 671/671 [00:00<00:00, 711.61it/s]

Creating new Ultralytics Settings v0.0.6 file
View Ultralytics Settings with 'yolo settings' or at 'C:\Users\Mo\AppData\Roaming\Ultralytics\settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

In [5]:
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="My-First-Project-2/data.yaml",
    epochs=30,
    imgsz=640,
    name="final_run"
)

Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 8.2MB/s 0.8s0.7s<0.0s.7s
Ultralytics 8.4.41  Python-3.13.0 torch-2.11.0+cpu CPU (12th Gen Intel Core i7-1250U)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=My-First-Project-2/data.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=30, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=final_run, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Mo\Desktop\smart-device-detection\runs\detect\final_run, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to 'C:\Users\Mo\AppData\Roaming\Ultralytics\Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 6.2MB/s 0.1s 0.1s<0.0s
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751897  ultralytics.nn.modules.head.Detect           [3, 16, None, [64, 128, 256]]
Model summary: 130 layers, 3,011,433 parameters, 3,011,417 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
train: Fast image access  (ping: 0.20.0 ms, read: 2.91.6 MB/s, size: 45.4 KB)
train: Scanning C:\Users\Mo\Desktop\smart-device-detection\My-First-Project-2\train\labels... 233 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 233/233 331.8it/s 0.7s0.1s
train: New cache created: C:\Users\Mo\Desktop\smart-device-detection\My-First-Project-2\train\labels.cache
WARNING Box and segment counts should be equal, but got len(segments) = 4, len(boxes) = 235. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
val: Fast image access  (ping: 0.10.0 ms, read: 3.81.6 MB/s, size: 47.7 KB)
val: Scanning C:\Users\Mo\Desktop\smart-device-detection\My-First-Project-2\valid\labels... 67 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 67/67 364.8it/s 0.2s.4s
val: New cache created: C:\Users\Mo\Desktop\smart-device-detection\My-First-Project-2\valid\labels.cache
WARNING Box and segment counts should be equal, but got len(segments) = 6, len(boxes) = 70. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\Mo\Desktop\smart-device-detection\runs\detect\final_run\labels.jpg...
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to C:\Users\Mo\Desktop\smart-device-detection\runs\detect\final_run
Starting training for 30 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/30         0G      1.077      2.957      1.527         21        640: 100% ━━━━━━━━━━━━ 15/15 4.8s/it 1:134.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 3.2s/it 9.7s9.0s7s
                   all         67         70    0.00345      0.955      0.535      0.371

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/30         0G     0.9743        2.1      1.464         23        640: 100% ━━━━━━━━━━━━ 15/15 4.9s/it 1:134.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.5s/it 7.4s6.8s8s
                   all         67         70    0.00579      0.955      0.783       0.52

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/30         0G     0.9415      1.675      1.395         20        640: 100% ━━━━━━━━━━━━ 15/15 4.9s/it 1:134.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.6s/it 7.7s7.2s7s
                   all         67         70      0.889      0.218      0.714      0.401

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/30         0G     0.9281      1.515      1.403         24        640: 100% ━━━━━━━━━━━━ 15/15 5.5s/it 1:225.4sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.8s/it 8.5s7.8s8s
                   all         67         70      0.763      0.759      0.766      0.472

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/30         0G      1.005      1.481      1.449         24        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:094.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s2s
                   all         67         70      0.763      0.772      0.837      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/30         0G     0.9766      1.386      1.414         26        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:094.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s4s
                   all         67         70      0.836      0.835      0.869      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/30         0G     0.9574      1.294      1.412         22        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:104.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 7.0s6.5s9s
                   all         67         70      0.779      0.817      0.838      0.544

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/30         0G     0.9497      1.274      1.381         22        640: 100% ━━━━━━━━━━━━ 15/15 4.8s/it 1:124.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 7.0s6.5s7s
                   all         67         70      0.749      0.717      0.788      0.452

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/30         0G     0.9328      1.258      1.392         23        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:104.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 7.0s6.5s4s
                   all         67         70      0.863      0.707      0.841      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/30         0G     0.9643      1.247      1.373         26        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:104.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.5s5s
                   all         67         70      0.958      0.705      0.885      0.575

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/30         0G     0.9274      1.141      1.357         24        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:114.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 7.0s6.5s8s
                   all         67         70      0.789       0.86      0.873       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/30         0G     0.9035      1.094      1.336         20        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:104.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.8s6.3s0s
                   all         67         70      0.912      0.809      0.902      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/30         0G     0.8714       1.05      1.324         23        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:104.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 7.0s6.5s9s
                   all         67         70      0.928      0.826      0.916      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/30         0G      0.947      1.119      1.381         30        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:114.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s0s
                   all         67         70      0.891      0.902       0.93       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/30         0G     0.8626     0.9842      1.298         27        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:114.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 7.0s6.5s7s
                   all         67         70      0.887      0.828      0.899      0.549

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/30         0G     0.8048     0.9298       1.27         28        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:104.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s0s
                   all         67         70      0.952      0.881      0.911      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/30         0G      0.921      0.946      1.349         21        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:104.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s0s
                   all         67         70       0.99      0.917      0.932      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/30         0G     0.8088     0.8669      1.267         23        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:104.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s8s
                   all         67         70      0.974       0.89      0.929      0.701

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/30         0G     0.7814     0.8567      1.249         21        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:104.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.4s/it 7.2s6.6s8s
                   all         67         70      0.971      0.915       0.94      0.697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/30         0G     0.7913     0.8124      1.236         25        640: 100% ━━━━━━━━━━━━ 15/15 4.7s/it 1:114.2sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s0s
                   all         67         70      0.993      0.919      0.944      0.704
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/30         0G     0.7096      1.049      1.313          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:093.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.8s6.3s9s
                   all         67         70      0.991      0.908      0.942      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/30         0G     0.6532     0.9651      1.296          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:094.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.8s6.3s0s
                   all         67         70       0.98      0.913      0.943      0.736

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/30         0G     0.6296     0.8429      1.279          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:094.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.4s/it 7.3s6.9s9s
                   all         67         70      0.972      0.918      0.936      0.728

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/30         0G     0.6511     0.8784      1.259          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:084.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.8s6.3s7s
                   all         67         70      0.992      0.932      0.947      0.731

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/30         0G     0.6086     0.8038      1.252          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:094.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s0s
                   all         67         70      0.981      0.944      0.946      0.743

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/30         0G     0.5887     0.7828      1.223          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:094.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s9s
                   all         67         70      0.993      0.944      0.946      0.731

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/30         0G     0.5646     0.7609      1.178          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:094.1sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.9s6.4s9s
                   all         67         70      0.994      0.944      0.948      0.753

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/30         0G     0.5402     0.7312      1.145          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:094.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.8s6.4s8s
                   all         67         70      0.996      0.944      0.949      0.753

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/30         0G     0.5218     0.7074      1.139          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:104.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 7.0s6.5s3s
                   all         67         70      0.996      0.944      0.949      0.752

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/30         0G     0.5066      0.705      1.154          9        640: 100% ━━━━━━━━━━━━ 15/15 4.6s/it 1:094.0sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.3s/it 6.8s6.3s9s
                   all         67         70      0.996      0.944      0.949      0.756

30 epochs completed in 0.651 hours.
Optimizer stripped from C:\Users\Mo\Desktop\smart-device-detection\runs\detect\final_run\weights\last.pt, 6.2MB
Optimizer stripped from C:\Users\Mo\Desktop\smart-device-detection\runs\detect\final_run\weights\best.pt, 6.2MB

Validating C:\Users\Mo\Desktop\smart-device-detection\runs\detect\final_run\weights\best.pt...
Ultralytics 8.4.41  Python-3.13.0 torch-2.11.0+cpu CPU (12th Gen Intel Core i7-1250U)
Model summary (fused): 73 layers, 3,006,233 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.1s/it 6.4s5.9ss
                   all         67         70      0.996      0.944      0.949      0.756
                laptop         27         29      0.995      0.931      0.944      0.748
               monitor         23         24      0.999      0.958      0.959      0.753

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x00000232654E80C0>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,     0.12134,     0.12134,           0],
       [          1,           1,           1, ...,     0.10345,     0.10345,           0],
       [          1,           1,           1, ...,           0,           0,           0]], shape=(3, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,

In [2]:
from ultralytics import YOLO

model = YOLO("runs/detect/final_run/weights/best.pt")

model("test.jpg", save=True)

image 1/1 c:\Users\Sami\Desktop\UNI\Applied Artificial Intelligence\smart-device-detection\smart-device-detection\test.jpg: 384x640 1 laptop, 138.8ms
Speed: 36.8ms preprocess, 138.8ms inference, 13.4ms postprocess per image at shape (1, 3, 384, 640)
Results saved to C:\Users\Sami\Desktop\UNI\Applied Artificial Intelligence\smart-device-detection\smart-device-detection\runs\detect\predict

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'laptop', 1: 'monitor', 2: 'phone'}
 obb: None
 orig_img: array([[[120,  76,  83],
         [120,  76,  83],
         [121,  77,  84],
         ...,
         [132,  63,  84],
         [130,  64,  83],
         [129,  63,  82]],

        [[120,  76,  83],
         [120,  76,  83],
         [121,  77,  84],
         ...,
         [132,  63,  84],
         [130,  64,  83],
         [130,  64,  83]],

        [[120,  76,  83],
         [120,  76,  83],
         [121,  77,  84],
         ...,
         [133,  64,  85],
         [130,  64,  83],
         [130,  64,  83]],

        ...,

        [[ 83, 165, 236],
         [ 82, 167, 237],
         [ 86, 168, 239],
         ...,
         [ 76, 121, 195],
         [ 77, 122, 196],
         [ 78, 123, 197]],

        [[ 93, 178, 246],
         [ 91, 178, 245],
         [ 92, 177, 245],
         ...,
         [ 76, 122, 199],
         [ 77, 123, 200],
         [ 78, 124, 201]],

        [[ 90, 177, 244],
         [ 89, 176, 243],
         [ 86, 173, 240],
         ...,
         [ 73, 121, 199],
         [ 73, 121, 199],
         [ 72, 120, 198]]], shape=(168, 300, 3), dtype=uint8)
 orig_shape: (168, 300)
 path: 'c:\\Users\\Sami\\Desktop\\UNI\\Applied Artificial Intelligence\\smart-device-detection\\smart-device-detection\\test.jpg'
 probs: None
 save_dir: 'C:\\Users\\Sami\\Desktop\\UNI\\Applied Artificial Intelligence\\smart-device-detection\\smart-device-detection\\runs\\detect\\predict'
 speed: {'preprocess': 36.759200011147186, 'inference': 138.8159999914933, 'postprocess': 13.434899999992922}]

In [6]:
from ultralytics import YOLO

model = YOLO("runs/detect/final_run/weights/best.pt")

model("test2.jpg", save=True)

image 1/1 c:\Users\Sami\Desktop\UNI\Applied Artificial Intelligence\smart-device-detection\smart-device-detection\test2.jpg: 640x640 1 monitor, 266.9ms
Speed: 46.6ms preprocess, 266.9ms inference, 31.6ms postprocess per image at shape (1, 3, 640, 640)
Results saved to C:\Users\Sami\Desktop\UNI\Applied Artificial Intelligence\smart-device-detection\smart-device-detection\runs\detect\predict-5

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'laptop', 1: 'monitor', 2: 'phone'}
 obb: None
 orig_img: array([[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]]], shape=(225, 225, 3), dtype=uint8)
 orig_shape: (225, 225)
 path: 'c:\\Users\\Sami\\Desktop\\UNI\\Applied Artificial Intelligence\\smart-device-detection\\smart-device-detection\\test2.jpg'
 probs: None
 save_dir: 'C:\\Users\\Sami\\Desktop\\UNI\\Applied Artificial Intelligence\\smart-device-detection\\smart-device-detection\\runs\\detect\\predict-5'
 speed: {'preprocess': 46.60880001029, 'inference': 266.9352999946568, 'postprocess': 31.568300008075312}]

In [8]:
from ultralytics import YOLO

model = YOLO("runs/detect/final_run/weights/best.pt")

model("test3.jpg", save=True)

image 1/1 c:\Users\Sami\Desktop\UNI\Applied Artificial Intelligence\smart-device-detection\smart-device-detection\test3.jpg: 512x640 1 phone, 224.1ms
Speed: 28.2ms preprocess, 224.1ms inference, 28.1ms postprocess per image at shape (1, 3, 512, 640)
Results saved to C:\Users\Sami\Desktop\UNI\Applied Artificial Intelligence\smart-device-detection\smart-device-detection\runs\detect\predict-3

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'laptop', 1: 'monitor', 2: 'phone'}
 obb: None
 orig_img: array([[[100, 137, 171],
         [102, 139, 173],
         [101, 136, 170],
         ...,
         [ 10,  15,  18],
         [ 19,  25,  30],
         [ 36,  45,  54]],

        [[ 99, 136, 170],
         [101, 138, 172],
         [100, 135, 169],
         ...,
         [ 10,  15,  18],
         [ 20,  26,  31],
         [ 36,  45,  54]],

        [[ 98, 135, 169],
         [100, 137, 171],
         [ 99, 134, 168],
         ...,
         [ 11,  16,  19],
         [ 21,  27,  32],
         [ 37,  46,  55]],

        ...,

        [[ 52,  80, 111],
         [ 41,  62,  83],
         [ 19,  28,  37],
         ...,
         [251, 254, 255],
         [234, 237, 241],
         [251, 254, 255]],

        [[ 55,  83, 114],
         [ 42,  63,  84],
         [ 20,  29,  38],
         ...,
         [251, 254, 255],
         [251, 254, 255],
         [231, 234, 238]],

        [[ 57,  85, 116],
         [ 44,  65,  86],
         [ 21,  30,  39],
         ...,
         [237, 239, 240],
         [253, 255, 255],
         [253, 255, 255]]], shape=(197, 255, 3), dtype=uint8)
 orig_shape: (197, 255)
 path: 'c:\\Users\\Sami\\Desktop\\UNI\\Applied Artificial Intelligence\\smart-device-detection\\smart-device-detection\\test3.jpg'
 probs: None
 save_dir: 'C:\\Users\\Sami\\Desktop\\UNI\\Applied Artificial Intelligence\\smart-device-detection\\smart-device-detection\\runs\\detect\\predict-3'
 speed: {'preprocess': 28.20829997654073, 'inference': 224.12179998354986, 'postprocess': 28.14619999844581}]

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

df = pd.read_csv("runs/detect/final_run/results.csv")
df.tail()

,epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,val/cls_loss,val/dfl_loss,lr/pg0,lr/pg1,lr/pg2
25,26,2035.65,0.58873,0.78275,1.22343,0.99284,0.94351,0.94636,0.73062,0.83238,0.89276,1.50911,0.000250,0.000250,0.000250
26,27,2112.34,0.56465,0.76087,1.17828,0.99448,0.94351,0.94796,0.75298,0.83728,0.88110,1.52388,0.000203,0.000203,0.000203
27,28,2188.69,0.54025,0.73117,1.14519,0.99575,0.94351,0.94913,0.75262,0.81797,0.85793,1.51428,0.000156,0.000156,0.000156
28,29,2265.63,0.52179,0.70740,1.13886,0.99639,0.94351,0.94922,0.75230,0.81543,0.83242,1.51288,0.000109,0.000109,0.000109
29,30,2341.72,0.50657,0.70503,1.15390,0.99607,0.94351,0.94921,0.75582,0.80329,0.81741,1.48941,0.000061,0.000061,0.000061

In [2]:
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="w0WrrKHoEIjB5SqpNv2E")
project = rf.workspace("sami-semir").project("my-first-project-q8ldn")
version = project.version(3)
dataset = version.download("yolov8")

Defaulting to user installation because normal site-packages is not writeable
Collecting roboflow
  Downloading roboflow-1.3.8-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: certifi in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (2026.4.22)
Collecting idna==3.7 (from roboflow)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: cycler in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (0.12.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (1.5.0)
Requirement already satisfied: matplotlib in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (3.10.9)
Requirement already satisfied: numpy>=1.18.5 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (2.4.4)
Collecting opencv-python-headless==4.10.0.84 (from roboflow)
  Using cached opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: Pillow>=7.1.2 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (12.2.0)
Collecting pi-heif<2 (from roboflow)
  Downloading pi_heif-1.3.0-cp312-cp312-win_amd64.whl.metadata (6.5 kB)
Collecting pillow-avif-plugin<2 (from roboflow)
  Downloading pillow_avif_plugin-1.5.5-cp312-cp312-win_amd64.whl.metadata (2.3 kB)
Requirement already satisfied: python-dateutil in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (2.9.0.post0)
Collecting python-dotenv (from roboflow)
  Using cached python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: requests in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (2.33.1)
Requirement already satisfied: six in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (1.17.0)
Requirement already satisfied: urllib3>=1.26.6 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (2.6.3)
Collecting tqdm>=4.41.0 (from roboflow)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: PyYAML>=5.3.1 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from roboflow) (6.0.3)
Collecting requests_toolbelt (from roboflow)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting filetype (from roboflow)
  Using cached filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting typer>=0.12.0 (from roboflow)
  Downloading typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: colorama in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tqdm>=4.41.0->roboflow) (0.4.6)
Collecting click>=8.2.1 (from typer>=0.12.0->roboflow)
  Using cached click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer>=0.12.0->roboflow)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer>=0.12.0->roboflow)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer>=0.12.0->roboflow)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->roboflow) (1.3.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->roboflow) (4.62.1)
Requirement already satisfied: packaging>=20.0 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->roboflow) (26.2)
Requirement already satisfied: pyparsing>=3 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib->roboflow) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from requests->roboflow) (3.4.7)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer>=0.12.0->roboflow)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mo\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from rich>=13.8.0->typer>=0.12.0->roboflow) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.12.0->roboflow)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading roboflow-1.3.8-py3-none-any.whl (207 kB)
Using cached idna-3.7-py3-none-any.whl (66 kB)
Using cached opencv_python_headless-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)
Downloading pi_heif-1.3.0-cp312-cp312-win_amd64.whl (1.9 MB)
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   -------------------------------- ------- 1.6/1.9 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 1.9/1.9 MB 5.1 MB/s eta 0:00:00
Downloading pillow_avif_plugin-1.5.5-cp312-cp312-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 1.7 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.9 MB 1.7 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/9.9 MB 1.7 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/9.9 MB 1.1 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.9 MB 1.1 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.9 MB 1.1 MB/s eta 0:00:09
   ----- ---------------------------------- 1.3/9.9 MB 684.4 kB/s eta 0:00:13
   ------- -------------------------------- 1.8/9.9 MB 906.5 kB/s eta 0:00:09
   ---------- ----------------------------- 2.6/9.9 MB 1.2 MB/s eta 0:00:06
   ------------ --------------------------- 3.1/9.9 MB 1.3 MB/s eta 0:00:06
   ------------- -------------------------- 3.4/9.9 MB 1.4 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.4 MB/s eta 0:00:05
   ---------------- ----------------------- 4.2/9.9 MB 1.4 MB/s eta 0:00:05
   ------------------ --------------------- 4.5/9.9 MB 1.4 MB/s eta 0:00:04
   ------------------- -------------------- 4.7/9.9 MB 1.4 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.9 MB 1.4 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/9.9 MB 1.4 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.4 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.9 MB 1.4 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.9 MB 1.5 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.9 MB 1.4 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.9 MB 1.4 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.4 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.9 MB 1.4 MB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 1.5 MB/s eta 0:00:02
   --------------------------------- ------ 8.4/9.9 MB 1.5 MB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 1.5 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 1.5 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 1.4 MB/s eta 0:00:00
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Downloading typer-0.25.1-py3-none-any.whl (58 kB)
Using cached filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Using cached python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached click-8.3.3-py3-none-any.whl (110 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pillow-avif-plugin, filetype, tqdm, shellingham, python-dotenv, pi-heif, opencv-python-headless, mdurl, idna, click, annotated-doc, markdown-it-py, rich, requests_toolbelt, typer, roboflow
  Attempting uninstall: idna
    Found existing installation: idna 3.13
    Uninstalling idna-3.13:
      Successfully uninstalled idna-3.13
Successfully installed annotated-doc-0.0.4 click-8.3.3 filetype-1.2.0 idna-3.7 markdown-it-py-4.2.0 mdurl-0.1.2 opencv-python-headless-4.10.0.84 pi-heif-1.3.0 pillow-avif-plugin-1.5.5 python-dotenv-1.2.2 requests_toolbelt-1.0.0 rich-15.0.0 roboflow-1.3.8 shellingham-1.5.4 tqdm-4.67.3 typer-0.25.1

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: C:\Users\Mo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

loading Roboflow workspace...
loading Roboflow project...

Downloading Dataset Version Zip in My-First-Project-3 to yolov8:: 100%|██████████| 17043/17043 [00:12<00:00, 1397.90it/s]

Extracting Dataset Version Zip to My-First-Project-3 in yolov8:: 100%|██████████| 741/741 [00:01<00:00, 469.70it/s]

In [7]:
from ultralytics import YOLO
model = YOLO("yolov8s.pt")

model.train(
    data="My-First-Project-3/data.yaml",
    epochs=50,
    imgsz=640,
    degrees=15,
    fliplr=0.5,
    hsv_v=0.4,
    name="improved_model"
)

New https://pypi.org/project/ultralytics/8.4.48 available  Update with 'pip install -U ultralytics'
Ultralytics 8.4.41  Python-3.12.10 torch-2.11.0+cpu CPU (12th Gen Intel Core i7-1250U)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=My-First-Project-3/data.yaml, degrees=15, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=improved_model, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Mo\Desktop\smart-device-detection\smart-device-detection\runs\detect\improved_model, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117209  ultralytics.nn.modules.head.Detect           [3, 16, None, [128, 256, 512]]
Model summary: 130 layers, 11,136,761 parameters, 11,136,745 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
train: Fast image access  (ping: 0.20.0 ms, read: 100.862.3 MB/s, size: 46.3 KB)
train: Scanning C:\Users\Mo\Desktop\smart-device-detection\smart-device-detection\My-First-Project-3\train\labels.cache... 258 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 258/258  0.0s
WARNING Box and segment counts should be equal, but got len(segments) = 4, len(boxes) = 260. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
val: Fast image access  (ping: 0.30.1 ms, read: 72.613.3 MB/s, size: 49.6 KB)
val: Scanning C:\Users\Mo\Desktop\smart-device-detection\smart-device-detection\My-First-Project-3\valid\labels.cache... 74 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 74/74  0.0s
WARNING Box and segment counts should be equal, but got len(segments) = 6, len(boxes) = 77. To resolve this only boxes will be used and all segments will be removed. To avoid this please supply either a detect or segment dataset, not a detect-segment mixed dataset.
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Plotting labels to C:\Users\Mo\Desktop\smart-device-detection\smart-device-detection\runs\detect\improved_model\labels.jpg...
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to C:\Users\Mo\Desktop\smart-device-detection\smart-device-detection\runs\detect\improved_model
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/50         0G      1.527      2.671      1.966          8        640: 100% ━━━━━━━━━━━━ 17/17 11.4s/it 3:14.2s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.6s/it 19.9s<16.6s
                   all         74         77      0.586      0.748      0.659      0.361

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/50         0G      1.282      1.718      1.745          6        640: 100% ━━━━━━━━━━━━ 17/17 11.0s/it 3:08.5s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.2s/it 18.6s<15.6s
                   all         74         77      0.784      0.731      0.787      0.359

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/50         0G      1.278      1.426      1.699          8        640: 100% ━━━━━━━━━━━━ 17/17 10.8s/it 3:03.4s5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.0s/it 18.0s<15.1s
                   all         74         77      0.664      0.381      0.304      0.119

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/50         0G      1.345      1.331      1.748          6        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 3:01.2s4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.0s/it 18.0s<15.0s
                   all         74         77      0.713      0.413      0.585      0.293

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/50         0G      1.358      1.346      1.761          6        640: 100% ━━━━━━━━━━━━ 17/17 10.8s/it 3:04.2s8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.1s/it 18.3s<15.2s
                   all         74         77      0.358      0.604      0.269      0.149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/50         0G      1.271      1.357      1.701          8        640: 100% ━━━━━━━━━━━━ 17/17 11.3s/it 3:12.3s2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.1s/it 18.2s<15.3s
                   all         74         77      0.558      0.489      0.436      0.209

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/50         0G      1.309       1.29      1.706          6        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:59.3s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.549      0.489      0.441      0.224

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/50         0G      1.317      1.263      1.716          7        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:59.7s2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.551      0.298      0.295      0.119

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/50         0G      1.427        1.3      1.789          4        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:58.2s1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.7s<14.8s
                   all         74         77      0.413      0.521      0.423      0.149

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/50         0G      1.311      1.135      1.689          5        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:58.0s1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.304       0.27      0.122     0.0361

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/50         0G      1.359       1.22      1.731          6        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:59.1s2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.6s<14.8s
                   all         74         77      0.846      0.699      0.811      0.459

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/50         0G      1.247      1.207      1.683          3        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:58.4s0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.7s<14.8s
                   all         74         77      0.715       0.71      0.694      0.357

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/50         0G      1.258      1.094      1.658          7        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:59.0s2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.818      0.775      0.812      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/50         0G      1.198      1.014      1.645          5        640: 100% ━━━━━━━━━━━━ 17/17 10.7s/it 3:03.2s4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.0s/it 18.0s<15.1s
                   all         74         77      0.817      0.761        0.8      0.403

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/50         0G      1.234      1.055      1.649          5        640: 100% ━━━━━━━━━━━━ 17/17 10.7s/it 3:01.1s6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.805      0.823      0.864      0.489

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/50         0G      1.163     0.9491      1.585          6        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:59.3s2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.7s<14.8s
                   all         74         77        0.8      0.862       0.88      0.493

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/50         0G      1.166     0.9346      1.581          6        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 2:59.1s4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.941      0.896      0.935      0.579

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/50         0G      1.171     0.9094       1.57          5        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:58.3s2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.2s/it 18.5s<15.5s
                   all         74         77      0.837      0.909       0.92      0.598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/50         0G      1.207     0.9875      1.624          3        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:58.0s1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.851      0.935      0.932       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/50         0G      1.119     0.8859       1.53          5        640: 100% ━━━━━━━━━━━━ 17/17 10.7s/it 3:02.4s6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.0s/it 18.0s<15.1s
                   all         74         77      0.618      0.896      0.613       0.39

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/50         0G      1.097     0.8432      1.543          5        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:59.1s2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.864      0.842      0.914      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/50         0G      1.065     0.8937      1.525          5        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 2:60.2s3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.0s/it 17.9s<15.0s
                   all         74         77      0.901      0.846      0.903        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/50         0G      1.113     0.8499      1.556          7        640: 100% ━━━━━━━━━━━━ 17/17 10.5s/it 2:59.1s3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.959      0.891      0.943      0.591

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/50         0G      1.165     0.8689       1.62          3        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 3:01.3s1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.7s<14.8s
                   all         74         77      0.963      0.901      0.942      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/50         0G      1.081     0.8341      1.532          6        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 2:60.2s6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.0s/it 17.9s<14.9s
                   all         74         77      0.892      0.857      0.914      0.592

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/50         0G      1.092     0.8687      1.535          5        640: 100% ━━━━━━━━━━━━ 17/17 10.7s/it 3:02.1s8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.0s/it 18.0s<15.1s
                   all         74         77      0.892       0.87      0.919       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/50         0G     0.9338     0.7433      1.439          8        640: 100% ━━━━━━━━━━━━ 17/17 10.7s/it 3:01.3s9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.934      0.919      0.946      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/50         0G      1.125     0.7371      1.533          4        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 3:00.4s3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.7s<14.8s
                   all         74         77      0.985      0.934      0.947      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/50         0G      1.087      0.782      1.541          5        640: 100% ━━━━━━━━━━━━ 17/17 10.9s/it 3:04.6s3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 6.4s/it 19.1s<15.9s
                   all         74         77      0.986      0.943      0.948      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/50         0G       1.07     0.8003      1.466          7        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 3:00.1s3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.7s<14.8s
                   all         74         77      0.987       0.88      0.943      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/50         0G      1.027     0.7667      1.484          6        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 3:01.2s3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.7s<14.9s
                   all         74         77      0.992      0.884       0.93      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/50         0G     0.9873     0.7277      1.436          5        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 3:00.3s6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.8s<14.9s
                   all         74         77      0.986      0.945      0.948      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/50         0G     0.9258     0.7345      1.435          3        640: 100% ━━━━━━━━━━━━ 17/17 10.6s/it 2:60.1s2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 5.9s/it 17.7s<14.9s

ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 1, 2])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x000002368C1EB800>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0],
       [          1,           1,           1, ...,           0,           0,           0]], shape=(3, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,

In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)

df = pd.read_csv("runs/detect/improved_model/results.csv")
df.tail()

,epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,val/cls_loss,val/dfl_loss,lr/pg0,lr/pg1,lr/pg2
45,46,9194.35,0.69559,0.41560,1.40827,0.99147,0.89738,0.94528,0.71012,0.91550,0.57040,1.57492,0.000156,0.000156,0.000156
46,47,9398.38,0.63598,0.37490,1.34362,0.99497,0.92418,0.94778,0.72160,0.90938,0.55929,1.58970,0.000127,0.000127,0.000127
47,48,9606.32,0.65723,0.39229,1.37254,0.99146,0.92704,0.94833,0.70942,0.90481,0.54199,1.59011,0.000099,0.000099,0.000099
48,49,9813.98,0.62279,0.35879,1.32615,0.98459,0.94834,0.94833,0.70131,0.92002,0.52409,1.60495,0.000071,0.000071,0.000071
49,50,10022.00,0.64056,0.37577,1.33275,0.98264,0.94909,0.94833,0.70944,0.90641,0.52147,1.57991,0.000043,0.000043,0.000043

In [3]:
from ultralytics import YOLO

model = YOLO("runs/detect/improved_model/weights/best.pt")

model("test4.jpg", save=True)

image 1/1 c:\Users\Sami\Desktop\Quick Share\New folder\smart-device-detection\smart-device-detection\smart-device-detection\test4.jpg: 384x640 4 phones, 297.3ms
Speed: 88.0ms preprocess, 297.3ms inference, 19.1ms postprocess per image at shape (1, 3, 384, 640)
Results saved to C:\Users\Sami\Desktop\Quick Share\New folder\smart-device-detection\smart-device-detection\smart-device-detection\runs\detect\predict-4

[ultralytics.engine.results.Results object with attributes:

 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'laptop', 1: 'monitor', 2: 'phone'}
 obb: None
 orig_img: array([[[177, 189, 167],
         [177, 189, 167],
         [178, 190, 168],
         ...,
         [154, 155, 121],
         [143, 143, 107],
         [134, 134,  98]],

        [[177, 189, 167],
         [177, 189, 167],
         [178, 190, 168],
         ...,
         [149, 150, 116],
         [137, 137, 101],
         [128, 128,  92]],

        [[177, 189, 167],
         [177, 189, 167],
         [178, 190, 168],
         ...,
         [142, 143, 109],
         [130, 130,  94],
         [122, 122,  86]],

        ...,

        [[150, 181, 204],
         [150, 181, 204],
         [150, 181, 204],
         ...,
         [170, 197, 218],
         [170, 197, 218],
         [170, 197, 218]],

        [[150, 181, 204],
         [150, 181, 204],
         [150, 181, 204],
         ...,
         [161, 188, 209],
         [160, 187, 208],
         [160, 187, 208]],

        [[151, 182, 205],
         [151, 182, 205],
         [151, 182, 205],
         ...,
         [163, 190, 211],
         [163, 190, 211],
         [163, 190, 211]]], shape=(168, 300, 3), dtype=uint8)
 orig_shape: (168, 300)
 path: 'c:\\Users\\Sami\\Desktop\\Quick Share\\New folder\\smart-device-detection\\smart-device-detection\\smart-device-detection\\test4.jpg'
 probs: None
 save_dir: 'C:\\Users\\Sami\\Desktop\\Quick Share\\New folder\\smart-device-detection\\smart-device-detection\\smart-device-detection\\runs\\detect\\predict-4'
 speed: {'preprocess': 88.04419999069069, 'inference': 297.2771000058856, 'postprocess': 19.146600010572}]